# Generated by Django 3.0.6 on 2020-05-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bendiciones_faccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('faccion', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=100)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('rasgo', models.CharField(max_length=100)),
                ('coste', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
